In [11]:
import pandas as pd
import plotly as pl

In [7]:
uploaded_file='DynamicsExport_638582166632440668.xlsx'

In [8]:
df = pd.read_excel(uploaded_file)
list_of_columns = df.columns.tolist()

In [9]:
df.

,Category,Item number,Product name,Date,Transaction time,Amount before tax,Category2,Operator ID,Weekday
0,Packaging Material,20003,Materials Work Order Pack,2024-05-22,2024-08-02 00:00:48,-4.85,Packaging Material,6110,4
1,Packaging Material,20003,Materials Work Order Pack,2024-05-22,2024-08-02 00:06:01,-4.85,Packaging Material,6110,4
2,Packaging Material,20003,Materials Work Order Pack,2024-05-22,2024-08-02 00:09:09,-4.85,Packaging Material,6110,4
3,Packaging Material,20003,Materials Work Order Pack,2024-05-22,2024-08-02 00:14:43,-4.85,Packaging Material,6110,4
4,Packaging Material,20003,Materials Work Order Pack,2024-05-22,2024-08-02 00:25:40,-4.85,Packaging Material,6110,4
...,...,...,...,...,...,...,...,...,...
31428,Packaging Material,20003,Materials Work Order Pack,2024-05-21,2024-08-02 23:27:56,-4.85,Packaging Material,6110,3
31429,Packaging Material,20003,Materials Work Order Pack,2024-05-21,2024-08-02 23:34:01,-4.85,Packaging Material,6110,3
31430,Packaging Material,20003,Materials Work Order Pack,2024-05-21,2024-08-02 23:38:33,-4.85,Packaging Material,6110,3
31431,Packaging Material,20003,Materials Work Order Pack,2024-05-21,2024-08-02 23:43:07,-4.85,Packaging Material,6110,3
31432,Packaging Material,20003,Materials Work Order Pack,2024-05-21,2024-08-02 23:47:56,-4.85,Packaging Material,6110,3